# shop 생성
POST http://localhost:8080/shops
Content-Type: application/json

{
  "name": "shop4",
  "branchName": "branch1",
  "hiddenString": "****"
}

###
GET http://localhost:8080/shops

###
GET http://localhost:8080/shops/1

###
PATCH http://localhost:8080/shops/1
Content-Type: application/json

{
  "name": "shop2"
}

### @RestResource(path = "name")
GET http://localhost:8080/shops/search/name?name=shop1

### @RestResource(path = "branchName")
GET http://localhost:8080/shops/search/branchName?branchName=branch1

### paging
http://localhost:8080/shops?page=1&size=2

### sort
http://localhost:8080/shops?page=0&size=5&sort=name,desc